### ISSUE TITLE
Router issues

### ISSUE THREAD

**Issue by prabhakarpshetty** [beaucarnes/mern-exercise-tracker-mongodb#2]
I am pretty new to FullStack and love your videos as they are excellent. Again thanks a lot for making the videos and it is so helpful. One of the issue I am facing is the below line of code is, I am not sure what I am missing. Appreciate your help.
//app.use("/exercises", exercisesRouter);
//app.use("/users", usersRouter);

D:\FullStack\Projects\ExcerciseTracker\node_modules\express\lib\router\index.js:458
      throw new TypeError('Router.use() requires a middleware function but got a ' + gettype(fn))
      ^
TypeError: Router.use() requires a middleware function but got a Object
    at Function.use (D:\FullStack\Projects\ExcerciseTracker\node_modules\express\lib\router\index.js:458:13)
    at Function.<anonymous> (D:\FullStack\Projects\ExcerciseTracker\node_modules\express\lib\application.js:220:21)
    at Array.forEach (<anonymous>)

**Comment by lumie31** [comment]
https://stackoverflow.com/questions/27465850/typeerror-router-use-requires-middleware-function-but-got-a-object

**Comment by filbrej** [comment]
I got this same error but found a fix!

Make sure in your routes folder that `exercises.js` and `users.js` both have `module.exports = router` at the bottom. I was missing it in one of mine and adding it got rid of the error. Hope this helps!
